# Basic Site Information
title: shieldjy
author: jiayi
post_author: Li Jiayi
description: Li Jiayi，student now majoring Electronics at Tongji Uni., Shanghai.
mail: lijiayi19971127@hotmail.com
about: "PhD Candidate
<p>Neuromorphic Devices</p>
<p>Nanyang Technological University - Singapore</p>"

# Site Appearance
logo: /assets/img/logo.png
icon: /favicon.ico
avatar:
  img: /assets/img/name.svg
  alt: Li Jiayi
  url: https://shieldjy.github.io/about/
  hint: Open my Curriculum Vitae
license:
  img: /assets/img/by-nc-sa.svg
default-theme: light
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Site Urls
baseurl: ""
url: "https://shieldjy.github.io"
links:
  - title: Blog
    url: /
  # - title: Articles
  #   url: /mind
  # - title: Friends
  #   url: /friends
  - title: Projects
    url: /projects
  - title: About
    url: /about/
  - title: Nonsense
    url: /nonsense/
links-light:
  - icon: users
    title: FRIENDS
    url: /friends
  - icon: rss
    title: RSS
    url: /feed.xml

# Social Accounts
github:
  username: shieldjy
  link: https://github.com/shieldjy
facebook:
  username: PlusOne97
twitter:
  username: PlusOne97
# stackoverflow:
#   link: https://stackoverflow.com/users/6233938/walterlv

# Visit Analysis
analytics:
  google: UA-162295889-1
  cnzz: cnzz_stat_icon_1278897451
# disqus:
#   name: walterlv
#   url: https://walterlv.com
# gitment:
#   owner: walterlv
#   client_id: 9a8b44a07f269679e9b5
#   client_secret: 3412cef75373074fd43b62462a7adef7ad1e2127
#   repo: walterlv.github.io
# leancloud:
#   appid: 2NpLNUTfjU4ey5wOeWPPiXXL-gzGzoHsz
#   appkey: OeA2qCtXi7ifv96UbMQ4J1kn

# Post Settings
excerpt_separator: ---
paginate: 30
per_page: 30
paginate_path: "/blog/page:num/"
collections:
  articles:
    output: true
  nonsenses:
    output: true
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: "Jiayi"
      permalink: "/post/:title.html"
  - scope:
      path: "_articles"
      type: "articles"
    values:
      layout: "post"
      author: "Jiayi"
      permalink: "/article/:title.html"
  - scope:
      path: "_nonsenses"
      type: "nonsenses"
    values:
      layout: "post"
      author: "Jiayi"
      permalink: "/nonsense/:title.html"
  - scope:
      path: "_private"
      type: "private"
    values:
      layout: "post"
      author: "Jiayi"
      permalink: "/private/:title.html"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jemoji

# Others
exclude: ['package.json', 'src', 'node_modules']
